# Generated by Django 2.0.6 on 2018-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='装备名')),
                ('hp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加生命')),
                ('mp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加真气')),
                ('band_up', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段上限')),
                ('band_down', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段下限')),
                ('atk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加外功')),
                ('mgk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加内功')),
                ('agi', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加轻功')),
                ('avd', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='附加回避率')),
                ('dex', models.IntegerField(blank=True, max_length=1000, null=True, verbose_name='附加会心率')),
                ('text', models.CharField(blank=True, max_length=65535, null=True, verbose_name='说明')),
                ('defense', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='防御_减伤')),
                ('vit', models.IntegerField(max_length=255, verbose_name='耐久')),
            ],
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='武学名')),
                ('hp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加生命')),
                ('mp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加真气')),
                ('band_up', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段上限')),
                ('band_down', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段下限')),
                ('atk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加外功')),
                ('mgk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加内功')),
                ('agi', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加轻功')),
                ('avd', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='附加回避率')),
                ('dex', models.IntegerField(blank=True, max_length=1000, null=True, verbose_name='附加会心率')),
                ('text', models.CharField(blank=True, max_length=65535, null=True, verbose_name='说明')),
                ('defense', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='防御_减伤')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色名')),
                ('hp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='生命')),
                ('mp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='真气')),
                ('band_up', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='波段上限')),
                ('band_down', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='波段下限')),
                ('atk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='外功')),
                ('mgk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='内功')),
                ('agi', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='轻功')),
                ('avd', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='回避率')),
                ('dex', models.IntegerField(blank=True, max_length=1000, null=True, verbose_name='会心率')),
                ('text', models.CharField(blank=True, max_length=65535, null=True, verbose_name='说明')),
                ('avatar', models.FileField(upload_to='avatar', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='武学名')),
                ('hp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加生命')),
                ('mp', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='附加真气')),
                ('band_up', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段上限')),
                ('band_down', models.IntegerField(blank=True, max_length=64, null=True, verbose_name='附加波段下限')),
                ('atk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加外功')),
                ('mgk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加内功')),
                ('agi', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='附加轻功')),
                ('avd', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='附加回避率')),
                ('dex', models.IntegerField(blank=True, max_length=1000, null=True, verbose_name='附加会心率')),
                ('text', models.CharField(blank=True, max_length=65535, null=True, verbose_name='说明')),
                ('defense', models.IntegerField(blank=True, max_length=65535, null=True, verbose_name='防御_减伤')),
            ],
        ),
    ]
