# Generated by Django 2.0.6 on 2018-09-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_auto_20180903_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='名字')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='生命')),
                ('mp', models.IntegerField(blank=True, null=True, verbose_name='真气')),
                ('bandup', models.IntegerField(blank=True, null=True, verbose_name='波段上限')),
                ('banddown', models.IntegerField(blank=True, null=True, verbose_name='波段下限')),
                ('atk', models.IntegerField(blank=True, null=True, verbose_name='功力')),
                ('str', models.IntegerField(blank=True, null=True, verbose_name='外功')),
                ('mgk', models.IntegerField(blank=True, null=True, verbose_name='内功')),
                ('agi', models.IntegerField(blank=True, null=True, verbose_name='轻功')),
                ('avd', models.IntegerField(blank=True, null=True, verbose_name='回避率')),
                ('dex', models.IntegerField(blank=True, null=True, verbose_name='会心率')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='说明')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('defense', models.IntegerField(blank=True, null=True, verbose_name='防御_减伤')),
                ('psy', models.IntegerField(verbose_name='灵力')),
            ],
            options={
                'verbose_name_plural': '灵力表',
                'verbose_name': '灵力表',
            },
        ),
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': '防具表', 'verbose_name_plural': '防具表'},
        ),
        migrations.AlterModelOptions(
            name='equit',
            options={'verbose_name': '角色装备表', 'verbose_name_plural': '角色装备表'},
        ),
        migrations.AlterModelOptions(
            name='heart',
            options={'verbose_name': '心法表', 'verbose_name_plural': '心法表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '技能表', 'verbose_name_plural': '技能表'},
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'verbose_name': '武器表', 'verbose_name_plural': '武器表'},
        ),
        migrations.AddField(
            model_name='armor',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='外功'),
        ),
        migrations.AddField(
            model_name='heart',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='外功'),
        ),
        migrations.AddField(
            model_name='role',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='外功'),
        ),
        migrations.AddField(
            model_name='skill',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='外功'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='str',
            field=models.IntegerField(blank=True, null=True, verbose_name='外功'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='atk',
            field=models.IntegerField(blank=True, null=True, verbose_name='功力'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='atk',
            field=models.IntegerField(blank=True, null=True, verbose_name='功力'),
        ),
        migrations.AlterField(
            model_name='role',
            name='atk',
            field=models.IntegerField(blank=True, null=True, verbose_name='功力'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='atk',
            field=models.IntegerField(blank=True, null=True, verbose_name='功力'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='atk',
            field=models.IntegerField(blank=True, null=True, verbose_name='功力'),
        ),
        migrations.AddField(
            model_name='spirit',
            name='equits',
            field=models.ManyToManyField(through='fight.Equit', to='fight.Role'),
        ),
        migrations.AddField(
            model_name='equit',
            name='spirit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fight.Spirit', verbose_name='装备灵器'),
        ),
    ]
