# Generated by Django 2.0.6 on 2018-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0005_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='role',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='img', verbose_name='头像'),
        ),
    ]
